default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ratelimiter_development

test:
  <<: *default
  database: ratelimiter_test

production:
  <<: *default
  database: ratelimiter_production
